await sleep(2500);
const q = s => document.querySelector(s);
const items = [...document.querySelectorAll('.gen-gallery-date-items > *')];
const target = items.find(e => /2026|lantern/i.test(e.title || e.getAttribute('data-prompt') || e.innerHTML)) || items.find(e => e.querySelector('img[src*="job-0007"]'));
log('items', items.length, 'target found', !!target);
const el = target || items[items.length - 1];
const star = el.querySelector('.gen-thumb-star');
const before = star.className;
star.click(); await sleep(600);
const after = star.className;
log('star class before/after', before, '|', after);
const gal = await fetch('/v1/gallery').then(r=>r.json());
const favs = JSON.stringify(gal).match(/"favorite":true/g) || [];
log('gallery favorites persisted', favs.length);
star.click(); await sleep(400);
el.click(); await sleep(700);
q('#gen-seed').value = '1'; q('#gen-seed').dispatchEvent(new Event('input',{bubbles:true}));
q('#gen-reuse-params').click(); await sleep(700);
log('after reuse: seed', q('#gen-seed').value, 'steps', q('#gen-steps').value, 'prompt', q('#gen-prompt').value.slice(0,60));
await shot('p2-12-history-reuse');
return { starToggled: before !== after, favoritesPersisted: favs.length, seed: q('#gen-seed').value, steps: q('#gen-steps').value, prompt: q('#gen-prompt').value.slice(0,80) };
